# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGBPadzpwJzDTBhtRJ-9KsRiZ-U2-Ln_
"""

!pip install transformers Biopython

import torch
from transformers import BertModel, BertTokenizer
from Bio import SeqIO
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load Model and Tokenizer
tokenizer = BertTokenizer.from_pretrained("Rostlab/prot_bert", do_lower_case=False)
model = BertModel.from_pretrained("Rostlab/prot_bert")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.eval()

def get_embeddings(fasta_file):
    sequences = []
    labels = []

    # 1. Parse FASTA
    for record in SeqIO.parse(fasta_file, "fasta"):
        # ProtBert needs spaces between AAs: "M E T..."
        seq = " ".join(list(str(record.seq)))
        sequences.append(seq)
        labels.append(int(record.description.split("label=")[-1]))

    all_embeddings = []

    # 2. Extract Features (Processing one by one to save memory)
    with torch.no_grad():
        for seq in sequences:
            ids = tokenizer(seq, return_tensors='pt', padding=True, truncation=True, max_length=512).to(device)
            output = model(**ids)

            # Global Average Pooling: Mean of all amino acid vectors
            embedding = output.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
            all_embeddings.append(embedding)

    return np.array(all_embeddings), np.array(labels)

# --- Updated Execution for Colab ---
print("Extracting training features...")
# Notice we changed the path to match where Colab stores uploaded files
X_train, y_train = get_embeddings("/content/train_data.fasta")

print("Extracting testing features...")
X_test, y_test = get_embeddings("/content/test_data.fasta")

print("Done! Feature shapes:", X_train.shape, X_test.shape)

#  Initialize the Random Forest with 'balanced' class weights
clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

#  Train the model
print("Training the Random Forest with balanced weights...")
clf.fit(X_train, y_train)

#  Make predictions
print("Predicting on test data...")
y_pred = clf.predict(X_test)

#  Show the results
print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred))

# 1. Initialize the Random Forest with 'balanced' class weights
# This helps if you have more of one type of protein than the other
clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

# 2. Train the model
print("Training the Random Forest with balanced weights...")
clf.fit(X_train, y_train)

# 3. Make predictions
print("Predicting on train data...")
y_pred_train = clf.predict(X_train)

# 4. Show the results
print("\n--- Classification Report ---")
print(classification_report(y_train, y_pred_train))

print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_train, y_pred_train))

import joblib

# Save the trained Random Forest classifier
joblib.dump(clf, 'protein_classifier_rf.joblib')

# Save the extracted features so you don't have to run ProtBert again
import numpy as np
np.save('X_train.npy', X_train)
np.save('X_test.npy', X_test)
np.save('y_train.npy', y_train)
np.save('y_test.npy', y_test)

print("Progress Saved! You can find these files in the left folder icon.")
#5 fold cross validation
from sklearn.model_selection import cross_val_score

# Performing 5-Fold Cross-Validation
print("Starting 5-Fold Cross-Validation...")
# We use 'clf' (your Random Forest) and the training embeddings
cv_scores = cross_val_score(clf, X_train, y_train, cv=5)

print("\n--- Cross-Validation Results ---")
print(f"Individual Fold Scores: {cv_scores}")
print(f"Mean Accuracy: {cv_scores.mean():.4f}")
print(f"Standard Deviation: {cv_scores.std():.4f}")

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, RocCurveDisplay

# 1. Get the probability scores for the positive class (Resistant)
# rf_classifier is your already trained Random Forest
y_probs = clf.predict_proba(X_test)[:, 1]

# 2. Calculate ROC metrics
fpr, tpr, thresholds = roc_curve(y_test, y_probs)
roc_auc = auc(fpr, tpr)

# 3. Plotting
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--') # The chance line

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (1 - Specificity)')
plt.ylabel('True Positive Rate (Sensitivity)')
plt.title('ROC Curve for Beta-Lactam Resistance Prediction')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

print(f"The Area Under the Curve (AUC) is: {roc_auc:.4f}")

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# 1. Get the probability scores for the 'Resistant' class (Class 1)
# We use clf because that is your model's name
y_probs = clf.predict_proba(X_test)[:, 1]

# 2. Calculate the ROC curve points
fpr, tpr, thresholds = roc_curve(y_test, y_probs)
roc_auc = auc(fpr, tpr)

# 3. Create the plot
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (1 - Specificity)')
plt.ylabel('True Positive Rate (Sensitivity)')
plt.title('ROC Curve: Beta-Lactam Resistance Prediction')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

print(f"Final Area Under the Curve (AUC): {roc_auc:.4f}")

!pip install matplotlib

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# 1. Get the probability scores for the 'Resistant' class (Class 1)
# We use clf because that is your model's name
y_probs = clf.predict_proba(X_test)[:, 1]

# 2. Calculate the ROC curve points
fpr, tpr, thresholds = roc_curve(y_test, y_probs)
roc_auc = auc(fpr, tpr)

# 3. Create the plot
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (1 - Specificity)')
plt.ylabel('True Positive Rate (Sensitivity)')
plt.title('ROC Curve: Beta-Lactam Resistance Prediction')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

print(f"Final Area Under the Curve (AUC): {roc_auc:.4f}")

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# 1. Get the probability scores for the 'Resistant' class (Class 1)
# We use clf because that is your model's name
y_probs = clf.predict_proba(X_test)[:, 1]

# 2. Calculate the ROC curve points
fpr, tpr, thresholds = roc_curve(y_test, y_probs)
roc_auc = auc(fpr, tpr)

# 3. Create the plot
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (1 - Specificity)')
plt.ylabel('True Positive Rate (Sensitivity)')
plt.title('ROC Curve: Beta-Lactam Resistance Prediction')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

print(f"Final Area Under the Curve (AUC): {roc_auc:.4f}")

# 1. Initialize the Random Forest with 'balanced' class weights
# This helps if you have more of one type of protein than the other
clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

# 2. Train the model
print("Training the Random Forest with balanced weights...")
clf.fit(X_train, y_train)

# 3. Make predictions
print("Predicting on test data...")
y_pred = clf.predict(X_test)

# 4. Show the results
print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred))

import torch
from transformers import BertModel, BertTokenizer
from Bio import SeqIO
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load Model and Tokenizer
tokenizer = BertTokenizer.from_pretrained("Rostlab/prot_bert", do_lower_case=False)
model = BertModel.from_pretrained("Rostlab/prot_bert")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.eval()

def get_embeddings(fasta_file):
    sequences = []
    labels = []

    # 1. Parse FASTA
    for record in SeqIO.parse(fasta_file, "fasta"):
        # ProtBert needs spaces between AAs: "M E T..."
        seq = " ".join(list(str(record.seq)))
        sequences.append(seq)
        labels.append(int(record.description.split("label=")[-1]))

    all_embeddings = []

    # 2. Extract Features (Processing one by one to save memory)
    with torch.no_grad():
        for seq in sequences:
            ids = tokenizer(seq, return_tensors='pt', padding=True, truncation=True, max_length=512).to(device)
            output = model(**ids)

            # Global Average Pooling: Mean of all amino acid vectors
            embedding = output.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
            all_embeddings.append(embedding)

    return np.array(all_embeddings), np.array(labels)

# --- Updated Execution for Colab ---
print("Extracting training features...")
# Notice we changed the path to match where Colab stores uploaded files
X_train, y_train = get_embeddings("/content/train_data.fasta")

print("Extracting testing features...")
X_test, y_test = get_embeddings("/content/test_data.fasta")

print("Done! Feature shapes:", X_train.shape, X_test.shape)

!pip install Biopython
#ProtBERT embedding
import torch
from transformers import BertModel, BertTokenizer
from Bio import SeqIO
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Model-loading
tokenizer = BertTokenizer.from_pretrained("Rostlab/prot_bert", do_lower_case=False)
model = BertModel.from_pretrained("Rostlab/prot_bert")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.eval()

def get_embeddings(fasta_file):
    sequences = []
    labels = []

    #  Parse FASTA
    for record in SeqIO.parse(fasta_file, "fasta"):
        seq = " ".join(list(str(record.seq)))
        sequences.append(seq)
        labels.append(int(record.description.split("label=")[-1]))

    all_embeddings = []

    #  Extract Features
    with torch.no_grad():
        for seq in sequences:
            ids = tokenizer(seq, return_tensors='pt', padding=True, truncation=True, max_length=512).to(device)
            output = model(**ids)

            # Global Average Pooling: Mean of all amino acid vectors
            embedding = output.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
            all_embeddings.append(embedding)

    return np.array(all_embeddings), np.array(labels)

# FEATURE EXTRACTION
print("Extracting training features...")
X_train, y_train = get_embeddings("/content/train_data.fasta")

print("Extracting testing features...")
X_test, y_test = get_embeddings("/content/test_data.fasta")

print("Done! Feature shapes:", X_train.shape, X_test.shape)
#random forest classifier
#  Initialize the Random Forest with 'balanced' class weights

clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

#  Train the model
print("Training the Random Forest with balanced weights...")
clf.fit(X_train, y_train)

#  Make predictions
print("Predicting on test data...")
y_pred = clf.predict(X_test)

#  Show the results
print("\n--- Classification Report ---")
print(classification_report(y_test, y_pred))

print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred))
#plot roc curve
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

#  Get the probability scores for the 'Resistant' class (Class 1)
# We use clf because that is your model's name
y_probs = clf.predict_proba(X_test)[:, 1]

#  Calculate the ROC curve points
fpr, tpr, thresholds = roc_curve(y_test, y_probs)
roc_auc = auc(fpr, tpr)

#  Create the plot
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (1 - Specificity)')
plt.ylabel('True Positive Rate (Sensitivity)')
plt.title('ROC Curve: Beta-Lactam Resistance Prediction')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
# --- ADD THIS LINE TO DOWNLOAD/SAVE ---
plt.savefig('ROC_Curve_Results.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"Final Area Under the Curve (AUC): {roc_auc:.4f}")
#feature extraction
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#  Get feature importances from the trained Random Forest
importances = clf.feature_importances_

#  Sort them in descending order and get the indices
indices = np.argsort(importances)[::-1]

#  Select the top 20 features
top_k = 20
top_indices = indices[:top_k]
top_importances = importances[top_indices]

#  Create feature names
feature_names = [f"ProtBert_Dim_{i}" for i in top_indices]

#  Plotting
plt.figure(figsize=(10, 8))
plt.barh(range(top_k), top_importances, align='center', color='skyblue')
plt.yticks(range(top_k), feature_names)
plt.gca().invert_yaxis()  # Put the most important at the top
plt.xlabel('Importance Score')
plt.title('Top 20 ProtBert Features by Random Forest Importance')
plt.grid(axis='x', linestyle='--', alpha=0.7)

# Save the plot for your report
plt.savefig('Feature_Importance_Top20.png', dpi=300, bbox_inches='tight')
plt.show()


# Corelation heatmap biological mapping of dimentions
import pandas as pd
from scipy.stats import spearmanr
import seaborn as sns
from Bio import SeqIO


# 1. We need the raw sequences to calculate Amino Acid frequencies.
# Let's re-extract just the sequences from your test FASTA file.
test_sequences = []
for record in SeqIO.parse("/content/test_data.fasta", "fasta"):
    test_sequences.append(str(record.seq))

# 2. Create a DataFrame from your X_test (the 1024 embeddings)
# This gives us a table where columns are ProtBert_Dim_0, ProtBert_Dim_1, etc.
df_test_embeddings = pd.DataFrame(X_test, columns=[f"ProtBert_Dim_{i}" for i in range(1024)])
df_test_embeddings['Sequence'] = test_sequences

# 3. Calculate Amino Acid Frequencies
amino_acids = ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']

def get_aa_freq(seq):
    return {aa: (seq.count(aa) / len(seq)) if len(seq) > 0 else 0 for aa in amino_acids}

print("Calculating amino acid frequencies for interpretation...")
aa_freq_df = df_test_embeddings['Sequence'].apply(get_aa_freq).apply(pd.Series)

# 4. Use the 'feature_names' (Top 20) generated from your RF code
corr_matrix = pd.DataFrame(index=feature_names, columns=amino_acids)

for feature in feature_names:
    dim_values = df_test_embeddings[feature]
    for aa in amino_acids:
        coef, _ = spearmanr(dim_values, aa_freq_df[aa])
        corr_matrix.loc[feature, aa] = coef

# 5. Plot the Correlation Heatmap
plt.figure(figsize=(15, 8))
sns.heatmap(corr_matrix.astype(float), annot=True, cmap='RdBu_r', center=0, fmt=".2f")
plt.title("Biological Mapping: Top 20 ProtBert Dimensions vs Amino Acid Frequency")
plt.xlabel("Amino Acid")
plt.ylabel("Top ProtBert Dimensions (from Random Forest)")
plt.savefig('Biological_Correlation_Heatmap.png', dpi=300,  bbox_inches='tight')
plt.show()

#virtual mutation test
import numpy as np
import torch

def virtual_mutation_test(sequence, pos_to_mutate, new_amino_acid):
    """
    sequence: The original protein string (e.g., 'MAVK...')
    pos_to_mutate: List of indices to change
    new_amino_acid: The AA to insert (e.g., 'T' for Threonine)
    """
    
    # 1. Create the mutated sequence
    seq_list = list(sequence.replace(" ", "")) # Remove spaces if present
    for pos in pos_to_mutate:
        if pos < len(seq_list):
            seq_list[pos] = new_amino_acid
    
    mutated_seq = " ".join(seq_list)
    original_seq = " ".join(list(sequence.replace(" ", "")))

    # 2. Extract embeddings for both
    def get_single_embedding(s):
        ids = tokenizer(s, return_tensors='pt', padding=True, truncation=True, max_length=512).to(device)
        with torch.no_grad():
            output = model(**ids)
        return output.last_hidden_state.mean(dim=1).squeeze().cpu().numpy().reshape(1, -1)

    orig_emb = get_single_embedding(original_seq)
    mut_emb = get_single_embedding(mutated_seq)

    # 3. Predict probabilities
    orig_prob = clf.predict_proba(orig_emb)[0][1]
    mut_prob = clf.predict_proba(mut_emb)[0][1]

    print(f"--- Mutation Results ({new_amino_acid}) ---")
    print(f"Original Resistance Probability: {orig_prob:.4f}")
    print(f"Mutated Resistance Probability:  {mut_prob:.4f}")
    print(f"Change: {((mut_prob - orig_prob) / orig_prob * 100):.2f}%")

# --- EXECUTION ---
# Pick a sequence from your test set that is currently labeled 'Non-Resistant'
sample_idx = 12 
sample_seq = test_sequences[sample_idx]

# Let's mutate 5 random positions to Threonine (which showed high importance in your heatmap)
positions = list(range(0, 50))
virtual_mutation_test(sample_seq, positions, 'T')
